//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Configuration.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-19 09:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class ConfigurationMap : EntityTypeConfiguration<Configuration>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——Configuration
        /// </summary>
        public ConfigurationMap()
        {
			// 主键
            this.HasKey(c => c.Id);
			this.Property(c => c.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(c => c.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("Configuration");
			//属性
			this.Property(c => c.Key).HasColumnName("Key");
			this.Property(c => c.Value).HasColumnName("Value");
        }
    }
}
