//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MobileCode.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 12:31
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MobileCodeMap : EntityTypeConfiguration<MobileCode>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MobileCode
        /// </summary>
        public MobileCodeMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MobileCode");
			//属性
            this.Property(m => m.MpUserId).HasColumnName("MpUserId");
			this.Property(m => m.Mobile).HasColumnName("Mobile").HasMaxLength(20);
			this.Property(m => m.Code).HasColumnName("Code").HasMaxLength(10);
            this.Property(m => m.Time).HasColumnName("Time");
            this.Property(m => m.OperationType).HasColumnName("OperationType");
            this.Property(m => m.Status).HasColumnName("Status");
        }
    }
}
