//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class Pos : BaseEntity
    {
        /// <summary>
        /// 实体类-Pos
        /// </summary>
        public Pos()
        {
        }
		
		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 经营地址
		/// </summary>
		public string VendorAddress { set; get; }

		/// <summary>
		/// 门店照片
		/// </summary>
		public string VendorPic { set; get; }

		/// <summary>
		/// 商户号
		/// </summary>
		public string VendorNO { set; get; }

		/// <summary>
		/// 商户名称
		/// </summary>
		public string VendorName { set; get; }

		/// <summary>
		/// 终端号
		/// </summary>
		public string TerminalNO { set; get; }

        /// <summary>
        /// 绑定的银行卡号
        /// </summary>
        public string BankNO { set; get; }

		/// <summary>
		/// 安装地址
		/// </summary>
		public string InstallAddress { set; get; }

		/// <summary>
		/// 扣率
		/// </summary>
        public string DeductRate { set; get; }

		/// <summary>
		/// POS查询手机绑定
		/// </summary>
		public string MobilePhones { set; get; }

		/// <summary>
		/// 用户查询商户关联用户id
		/// </summary>
		public string MpUserIds { set; get; }
    }
}
