//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PosApply : BaseEntity
    {
        /// <summary>
        /// 实体类-PosApply
        /// </summary>
        public PosApply()
        {
        }
		
		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 关联posid
		/// </summary>
		public Guid PosAuthId { set; get; }

		/// <summary>
		/// 经营地址
		/// </summary>
		public string VendorAddress { set; get; }

		/// <summary>
		/// 门店照片
		/// </summary>
		public string VendorPic { set; get; }

		/// <summary>
		/// 商户名称
		/// </summary>
		public string VendorName { set; get; }

		/// <summary>
		/// 安装地址
		/// </summary>
		public string InstallAddress { set; get; }

		/// <summary>
		/// 扣率
		/// </summary>
		public string DeductRate { set; get; }

		private DateTime repealdate;
		/// <summary>
		/// 撤消日期
		/// </summary>
		public DateTime RepealDate
		{
			set { repealdate = value; }
			get
			{
				if (repealdate < new DateTime(1900, 1, 1))
				{
					repealdate = new DateTime(1900, 1, 1);
				}
				return repealdate;
			}
		}

		/// <summary>
		/// 申请状态［0-正常，1-被撤销］
		/// </summary>
		public int Status { set; get; }

		/// <summary>
		/// 分配状态［0-无任何处理，1-已分配］
		/// </summary>
		public int AssignStatus { set; get; }

		/// <summary>
		/// 分配支行
		/// </summary>
		public string AssignSubbranch { set; get; }

		/// <summary>
		/// 分配客户经理
		/// </summary>
		public string AssignCustomerManager { set; get; }

		/// <summary>
		/// 客户经理手机
		/// </summary>
		public string CustomerManagerPhone { set; get; }

		/// <summary>
		/// 受理状态［0-未受理，1-已通过，2-未通过，3-受理中］（管理员拒绝用户请求也是改变此状态，把受理状态置成未通过即标识拒绝）
		/// </summary>
		public int ProcessStatus { set; get; }

		/// <summary>
		/// 受理结果
		/// </summary>
		public string ProcessResult { set; get; }

		private DateTime processdate;
		/// <summary>
		/// 受理日期
		/// </summary>
		public DateTime ProcessDate
		{
			set { processdate = value; }
			get
			{
				if (processdate < new DateTime(1900, 1, 1))
				{
					processdate = new DateTime(1900, 1, 1);
				}
				return processdate;
			}
		}

		/// <summary>
		/// 回访满意度[1:满意，2:一般，3:不满意]
		/// </summary>
		public int ReturnStatus { set; get; }

		private DateTime returnvisitdate;
		/// <summary>
		/// 回访日期
		/// </summary>
		public DateTime ReturnVisitDate
		{
			set { returnvisitdate = value; }
			get
			{
				if (returnvisitdate < new DateTime(1900, 1, 1))
				{
					returnvisitdate = new DateTime(1900, 1, 1);
				}
				return returnvisitdate;
			}
		}

		/// <summary>
		/// 回访结果
		/// </summary>
		public string ReturnVisitResult { set; get; }


        #region not mapped

        /// <summary>
        /// 是否已经过期[0:未过期，1:已过期]
        /// </summary>
        [NotMapped]
        public int? PastDueId { set; get; }

        /// <summary>
        /// 申请开始时间
        /// </summary>
        [NotMapped]
        public DateTime? StartDate { set; get; }

        /// <summary>
        /// 申请结束时间
        /// </summary>
        [NotMapped]
        public DateTime? EndDate { set; get; }

        #endregion
    }
}
