//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosAuth.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PosAuth : BaseEntity
    {
        /// <summary>
        /// 实体类-PosAuth
        /// </summary>
        public PosAuth()
        {
        }
        /// <summary>
        /// 关联用户id
        /// </summary>
        public Guid MpUserId { get; set; }
		/// <summary>
		/// 姓名
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 手机
		/// </summary>
		public string MobilePhone { set; get; }

		/// <summary>
		/// 查否认证
		/// </summary>
		public int IsAuth { set; get; }
    }
}
