//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MobileCode.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 12:32
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;


namespace Ocean.Services
{
    public class MobileCodeService : ServiceBase<MobileCode>, IMobileCodeService
    {
		public MobileCodeService(IRepository<MobileCode> mobileCodeRepository, IDbContext context)
            : base(mobileCodeRepository, context)
        {
        }

        public MobileCode GetMobileCode(string mobile, string code, Guid mpUserId, int operationType)
        {
            return GetUnique(m => m.Mobile == mobile && m.Code == code && m.MpUserId == mpUserId && m.OperationType == operationType && m.Status == 0 && m.Time <= 5);
        }

        public MobileCode GetMobileCode(Guid mpUserId, int operationType)
        {
            return GetUnique(m => m.MpUserId == mpUserId && m.Status == 0 && m.Time <= 5 && m.OperationType == operationType, "CreateDate", false);
        }

        public int GetMobileCodeCount(string mobile, int operationType)
        {
            Dictionary<string,object> parms=new Dictionary<string,object>();
            parms.Add("Mobile",mobile);
            parms.Add("OperationType", operationType);
            return GetCount(" where Mobile=@Mobile and OperationType=@OperationType and convert(varchar(10),CreateDate,120)='" + DateTime.Now.ToString("yyyy-MM-dd") + "'", parms);
        }
        public int GetMobileCodeCount(Guid mpUserId, int operationType)
        {
            Dictionary<string, object> parms = new Dictionary<string, object>();
            parms.Add("MpUserId", mpUserId);
            parms.Add("OperationType", operationType);
            return GetCount(" where MpUserId=@MpUserId and OperationType=@OperationType and convert(varchar(10),CreateDate,120)='" + DateTime.Now.ToString("yyyy-MM-dd") + "'", parms);
        }
    }
}
