//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Loan.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-01-26 09:55
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;
using Ocean.Entity.DTO;

namespace Ocean.Services
{
    public interface ILoanService : IService<Loan>
    {
        /// <summary>
        /// 根据搜索条件获取分页数据
        /// </summary>
        PagedList<Loan> GetPageList(int pageIndex, int pageSize, LoanDTO loanDTO);

        /// <summary>
        /// 根据用户Id获取最新贷款申请记录
        /// </summary>
        Loan GetNewestLoanApplyByMpUserId(Guid mpUserId);
    }
}
