//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Plugin.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class VoteItem : BaseEntity
    {
        /// <summary>
        /// 实体类-Plugin
        /// </summary>
        public VoteItem()
        {
        }

        /// <summary>
        /// 关联插件ID(用户免费与收费只存在一种)
        /// </summary>
        public Guid VoteParentId { set; get; }

        /// <summary>
        /// 自定义名称
        /// </summary>
        public string ItemName { set; get; }

        /// <summary>
        /// 自定义名称
        /// </summary>
        public string ItemPic { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public int VoteCount { set; get; }

        /// <summary>
        /// 自定义名称
        /// </summary>
        public string ItemAuthor { set; get; }


        /// <summary>
        /// 自定义名称
        /// </summary>
        public string ItemSummary { set; get; }

        
    }
}
