//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Plugin.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class VoteBase : BaseEntity
    {
        /// <summary>
        /// 实体类-Plugin
        /// </summary>
        public VoteBase()
        {
        }

        /// <summary>
        /// 自定义名称
        /// </summary>
        public string VoteTitle { set; get; }


        public int VoteCount { set; get; }

        private DateTime voteStartDate;
        /// <summary>
        /// 投票开始日期
        /// </summary>
        public DateTime VoteStartDate
        {
            set { voteStartDate = value; }
            get
            {
                if (voteStartDate < new DateTime(1900, 1, 1))
                {
                    voteStartDate = new DateTime(1900, 1, 1);
                }
                return voteStartDate;
            }
        }

        private DateTime voteEndDate;
        /// <summary>
        /// 投票截止日期
        /// </summary>
        public DateTime VoteEndDate
        {
            set { voteEndDate = value; }
            get
            {
                if (voteEndDate < new DateTime(1900, 1, 1))
                {
                    voteEndDate = new DateTime(1900, 1, 1);
                }
                return voteEndDate;
            }
        }
        
    }
}
