//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpDiyMenu.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-20 09:39
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class MpDiyMenu : BaseEntity
    {
        /// <summary>
        /// 实体类-MpDiyMenu
        /// </summary>
        public MpDiyMenu()
        {
        }
		
		/// <summary>
		/// 
		/// </summary>
		public Guid MpID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid ParentID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string BtnName { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string BtnType { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string BtnKey { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public bool IsDeleted { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid MaterialID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public int SortIndex { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid CreateUser { set; get; }

		private DateTime updatedate;
		/// <summary>
		/// 
		/// </summary>
		public DateTime UpdateDate
		{
			set { updatedate = value; }
			get
			{
				if (updatedate < new DateTime(1900, 1, 1))
				{
					updatedate = new DateTime(1900, 1, 1);
				}
				return updatedate;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public Guid UpdateUser { set; get; }
    }
}
