//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpMaterial.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-08 17:25
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using Newtonsoft.Json;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class MpMaterial : BaseEntity
    {
        /// <summary>
        /// 实体类-MpMaterial
        /// </summary>
        public MpMaterial()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public Guid MpID { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public bool IsDynamic { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string DynamicType { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string ApiUrl { set; get; }

        /// <summary>
        /// 
        /// </summary>
        [JsonConverter(typeof(HtmlEncodingConverter))]
        public string PostData { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public int MedeaID { set; get; }

        public int IsMul { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public int TypeID { set; get; }
        public int IsChat { set; get; }
        /// <summary>
        /// 
        /// </summary>
        public string TypeName { set; get; }

        private DateTime lastmedeadate;
        /// <summary>
        /// 
        /// </summary>
        public DateTime LastMedeaDate
        {
            set { lastmedeadate = value; }
            get
            {
                if (lastmedeadate < new DateTime(1900, 1, 1))
                {
                    lastmedeadate = new DateTime(1900, 1, 1);
                }
                return lastmedeadate;
            }
        }

        private DateTime upatedate;
        /// <summary>
        /// 
        /// </summary>
        public DateTime UpateDate
        {
            set { upatedate = value; }
            get
            {
                if (upatedate < new DateTime(1900, 1, 1))
                {
                    upatedate = new DateTime(1900, 1, 1);
                }
                return upatedate;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public Guid CreateUser { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public Guid UpdateUser { set; get; }


        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<MpMaterialItem> MpMaterialItems { get; set; }
    }
}
