//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpMaterialItem.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-08 17:25
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using Newtonsoft.Json;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class MpMaterialItem : BaseEntity
    {
        /// <summary>
        /// 实体类-MpMaterialItem
        /// </summary>
        public MpMaterialItem()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public Guid MaterialID { set; get; }
        [JsonIgnore]
        public virtual MpMaterial MpMaterial { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [JsonConverter(typeof(HtmlEncodingConverter))]
        public string ReplyContent { set; get; }

        /// <summary>
        /// 
        /// </summary>
        [JsonConverter(typeof(HtmlEncodingConverter))]
        public string Title { set; get; }

        /// <summary>
        /// 
        /// </summary>
        [JsonConverter(typeof(HtmlEncodingConverter))]
        public string Description { set; get; }

        /// <summary>
        /// 
        /// </summary>
        [JsonConverter(typeof(HtmlEncodingConverter))]
        public string Summary { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string MusicUrl { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string HQMusicUrl { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string PicUrl { set; get; }

        /// <summary>
        /// 
        /// </summary>
        public string Url { set; get; }
    }
}
