//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpRelpyCategory.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-20 09:39
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class MpRelpyCategory : BaseEntity
    {
        /// <summary>
        /// 实体类-MpRelpyCategory
        /// </summary>
        public MpRelpyCategory()
        {
        }
		
		/// <summary>
		/// 
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Description { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public bool Userable { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string DesImg { set; get; }
    }
}
