//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpUserGroup.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 13:44
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class MpUserGroup : BaseEntity
    {
        /// <summary>
        /// 实体类-MpUserGroup
        /// </summary>
        public MpUserGroup()
        {
        }
		
		/// <summary>
		/// 
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Description { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public int GID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public int OrderIndex { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public bool IsSystem { set; get; }

		private DateTime updatedate;
		/// <summary>
		/// 
		/// </summary>
		public DateTime UpdateDate
		{
			set { updatedate = value; }
			get
			{
				if (updatedate < new DateTime(1900, 1, 1))
				{
					updatedate = new DateTime(1900, 1, 1);
				}
				return updatedate;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public Guid CreateUser { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid UpdateUser { set; get; }
    }
}
