//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 16:28
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class MpUser : BaseEntity
    {
        /// <summary>
        /// 实体类-MpUser
        /// </summary>
        public MpUser()
        {
        }

        private ICollection<KfMeeting> _kfMeetings;

        private ICollection<Loan> _loans;
		
		/// <summary>
		/// 
		/// </summary>
		public string OpenID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid MpID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public Guid MpGroupID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string NickName { set; get; }

		/// <summary>
		/// 
		/// </summary>
        public string OrginID { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string RemarkName { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public int Sex { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Language { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string City { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Province { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Country { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string HeadImgUrl { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public bool IsSubscribe { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public int UserState { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public double LocationX { set; get; }

		/// <summary>
		/// 
		/// </summary>
        public double LocationY { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string LocationLabel { set; get; }

		private DateTime subscribedate;
		/// <summary>
		/// 
		/// </summary>
		public DateTime SubscribeDate
		{
			set { subscribedate = value; }
			get
			{
				if (subscribedate < new DateTime(1900, 1, 1))
				{
					subscribedate = new DateTime(1900, 1, 1);
				}
				return subscribedate;
			}
		}

		private DateTime lastvisitdate;

		/// <summary>
		/// 
		/// </summary>
		public DateTime LastVisitDate
		{
			set { lastvisitdate = value; }
			get
			{
				if (lastvisitdate < new DateTime(1900, 1, 1))
				{
					lastvisitdate = new DateTime(1900, 1, 1);
				}
				return lastvisitdate;
			}
		}

        /// <summary>
        /// 密匙(长度8位)
        /// </summary>
        public string PasswordKey { set; get; }

        /// <summary>
        /// 唯一登录标识
        /// </summary>
        public string SessionId { set; get; }

        /// <summary>
        /// 证件号码
        /// </summary>
        public string PassportNO { set; get; }

        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// 手机号码
        /// </summary>
        public string MobilePhone { set; get; }

        /// <summary>
        /// 是否身份认证
        /// </summary>
        public int IsAuth { get; set; }
        public int SceneId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// [Key, ForeignKey("Role")]
        public Guid AdminId { set; get; }

        private ICollection<Admin> _admins;
        /// <summary>
        /// 管理员集
        /// </summary>
        public virtual ICollection<Admin> Admins
        {
            get { return _admins ?? (_admins = new List<Admin>()); }
            protected set { _admins = value; }
        }
        /// <summary>
        /// 贷款集
        /// </summary>
        public virtual ICollection<Loan> Loans
        {
            get { return _loans ?? (_loans = new List<Loan>()); }
            protected set { _loans = value; }
        }

        /// <summary>
        /// 客服会话集
        /// </summary>
        public virtual ICollection<KfMeeting> KfMeetings
        {
            get { return _kfMeetings ?? (_kfMeetings = new List<KfMeeting>()); }
            protected set { _kfMeetings = value; }
        }
    }
}
