//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class ScoreTradeInfo : BaseEntity
    {
        /// <summary>
        /// 实体类-ScoreTradeInfo
        /// </summary>
        public ScoreTradeInfo()
        {
        }

        /// <summary>
        /// 姓名
        /// </summary>
        public string ClientName { set; get; }

        /// <summary>
        /// 手机
        /// </summary>
        public string ClientPhone { set; get; }
        private DateTime tradeTime;
		/// <summary>
		/// 撤消日期
		/// </summary>
        public DateTime TradeTime
		{
            set { tradeTime = value; }
			get
			{
                if (tradeTime < new DateTime(1900, 1, 1))
				{
                    tradeTime = new DateTime(1900, 1, 1);
				}
                return tradeTime;
			}
		}

		/// <summary>
		/// 交易笔数［0-正常，1-被撤销］
		/// </summary>
        public int TradeCount { set; get; }

		/// <summary>
        /// 是否已经统计［0-未跑，1-已跑］
		/// </summary>
        public int IsStatic { set; get; }

		
    }
}
