//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginResult.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class ScorePluginResult : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginResult
        /// </summary>
        public ScorePluginResult()
        {
        }

        /// <summary>
        /// 用户ID
        /// </summary>
        public Guid MpUserId { set; get; }

        /// <summary>
        /// 插件ID
        /// </summary>
        public Guid PluginId { set; get; }

        /// <summary>
        /// 用户名
        /// </summary>
        public string UserName { set; get; }

        /// <summary>
        /// 真实姓名
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// 邮箱地址
        /// </summary>
        public int Type { set; get; }

        /// <summary>
        /// 电话号码
        /// </summary>
        public string Phone { set; get; }

        /// <summary>
        /// 手机号码
        /// </summary>
        public string MobilePhone { set; get; }

        /// <summary>
        /// 领奖详细地址
        /// </summary>
        public string Address { set; get; }

        /// <summary>
        /// 结果SN码
        /// </summary>
        public string SN { set; get; }

        /// <summary>
        /// 是否已使用｜领奖...等状态
        /// </summary>
        public int IsUse { set; get; }

        /// <summary>
        /// 插件提交信息简述
        /// </summary>
        public string Summary { set; get; }

        /// <summary>
        /// 插件提交XML存储值
        /// </summary>
        public string Value { set; get; }
    }
}
