//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosAuth.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class ScoreUser : BaseEntity
    {
        /// <summary>
        /// 实体类-ScoreUser
        /// </summary>
        public ScoreUser()
        {
        }
        /// <summary>
        /// 关联用户id
        /// </summary>
        public Guid MpUserId { get; set; }
		/// <summary>
		/// 姓名
		/// </summary>
        public string ClientName { set; get; }

		/// <summary>
		/// 手机
		/// </summary>
        public string ClientPhone { set; get; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string RecommendName { set; get; }

        /// <summary>
        /// 手机
        /// </summary>
        public string RecommendPhone { set; get; }

		/// <summary>
		/// 当前积分
		/// </summary>
        public int CurrentScore { set; get; }
        /// <summary>
        /// 推荐积分
        /// </summary>
        public int RecommendScore { set; get; }
        /// <summary>
        /// 当前交易所得积分
        /// </summary>
        public int DealScore { set; get; }
        /// <summary>
        /// 是否员工
        /// </summary>
        public int IsEmployee { set; get; }

        private DateTime lastUpdateDateTime;
        /// <summary>
        /// 最后更新 交易的时间
        /// </summary>
        public DateTime LastUpdateDateTime
        {
            set { lastUpdateDateTime = value; }
            get
            {
                if (lastUpdateDateTime < new DateTime(1900, 1, 1))
                {
                    lastUpdateDateTime = new DateTime(1900, 1, 1);
                }
                return lastUpdateDateTime;
            }
        }

        /// <summary>
        /// 接收电话
        /// </summary>
        public string RecvPhone { set; get; }

        /// <summary>
        /// 接收姓名
        /// </summary>
        public string RecvName { set; get; }

        /// <summary>
        /// 接收地址
        /// </summary>
        public string RecvAddress { set; get; }

    }
}
