//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class ScoreConsumeInfo : BaseEntity
    {
        /// <summary>
        /// 实体类-Pos
        /// </summary>
        public ScoreConsumeInfo()
        {
        }
		
		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
        /// 消耗类型 0:抽奖 1:兑换 2:转让 3:交易收入
		/// </summary>
        public int ConsumeType { set; get; }

		/// <summary>
        /// 消耗积分
		/// </summary>
        public int ConsumePoints { set; get; }

        private DateTime consumeDateTime;
		/// <summary>
		/// 商户号
		/// </summary>
        public DateTime ConsumeDateTime
        {
            set { consumeDateTime = value; }
            get
            {
                if (consumeDateTime < new DateTime(1900, 1, 1))
                {
                    consumeDateTime = new DateTime(1900, 1, 1);
                }
                return consumeDateTime;
            }
        }

		/// <summary>
		/// 商户名称
		/// </summary>
        public string Summary { set; get; }

		
    }
}
