//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosAuth.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class ScoreStoreItem : BaseEntity
    {
        /// <summary>
        /// 实体类-ScoreStoreItem
        /// </summary>
        public ScoreStoreItem()
        {
        }
        /// <summary>
        /// Baseid
        /// </summary>
        public Guid BaseId { get; set; }
		/// <summary>
		/// 物品名称
		/// </summary>
        public string ItemName { set; get; }

		/// <summary>
		/// 物品图片
		/// </summary>
        public string ItemPic { set; get; }

		/// <summary>
		/// 消耗积分
		/// </summary>
        public int NeedPoint { set; get; }
        /// <summary>
        /// 总共数量
        /// </summary>
        public int TotalCount { set; get; }
        /// <summary>
        /// 剩余数量
        /// </summary>
        public int LeftCount { set; get; }

        /// <summary>
        /// 物品描述
        /// </summary>
        public string ItemSummary { set; get; }
        /// <summary>
        /// 概率
        /// </summary>
        public string PrizePercent { set; get; }
        /// <summary>
        /// 抽奖角度
        /// </summary>
        public string PrizeAngle { set; get; }/// <summary>
        /// 奖项名
        /// </summary>
        public string PluginName { set; get; }//
        /// 奖项别名
        /// </summary>
        public string AliasName { set; get; }/// <summary>
        /// 是否虚拟积分
        /// </summary>
        public int VirtualGift { set; get; }
    }
}
