//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="FunongbaoApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 14:21
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class FunongbaoApplyMap : EntityTypeConfiguration<FunongbaoApply>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——FunongbaoApply
        /// </summary>
        public FunongbaoApplyMap()
        {
			// 主键
            this.HasKey(f => f.Id);
			this.Property(f => f.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(f => f.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("FunongbaoApply");
			//属性
			this.Property(f => f.FunongbaoId).HasColumnName("FunongbaoId");
            this.Property(f => f.PreGroupLimit).HasColumnName("PreGroupLimit");
            this.Property(f => f.PreLimit).HasColumnName("PreLimit");
            this.Property(f => f.PreRates).HasColumnName("PreRates");
			this.Property(f => f.ApplyLimit).HasColumnName("ApplyLimit");
			this.Property(f => f.ApplyRates).HasColumnName("ApplyRates");
			this.Property(f => f.ChangedLimit).HasColumnName("ChangedLimit");
			this.Property(f => f.ChangedRates).HasColumnName("ChangedRates");
			this.Property(f => f.ProcessStatus).HasColumnName("ProcessStatus");
            this.Property(f => f.ProcessResult).HasColumnName("ProcessResult");
            this.Property(f => f.ApplyStatus).HasColumnName("ApplyStatus");
            this.Property(f => f.GroupApplyStatus).HasColumnName("GroupApplyStatus");
            this.Property(f => f.ApplyDate).HasColumnName("ApplyDate");
			this.Property(f => f.FinishDate).HasColumnName("FinishDate");
			this.Property(f => f.Subbranch).HasColumnName("Subbranch");
			this.Property(f => f.Marketer).HasColumnName("Marketer");
            this.Property(f => f.LimitProgramme).HasColumnName("LimitProgramme");
			this.Property(f => f.SuggestionLimit).HasColumnName("SuggestionLimit");
            this.Property(f => f.NoticeStatus).HasColumnName("NoticeStatus");
            // 关系
            this.HasRequired(fa => fa.RFunongbao).WithMany(f => f.FunongbaoApplies).HasForeignKey(p => p.FunongbaoId).WillCascadeOnDelete(false);
        }
    }
}
