//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="FunongbaoApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 14:23
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Entity.DTO;
using Ocean.Core;


namespace Ocean.Services
{
    public interface IFunongbaoApplyService : IService<FunongbaoApply>
    {
        /// <summary>
        /// 根据搜索条件获取分页数据
        /// </summary>
        PagedList<FunongbaoApply> GetPageList(int pageIndex, int pageSize, FunongbaoApply funongBaoApplyDTO);
        PagedList<FunongbaoApply> GetPageList(int PageIndex, int PageSize, Guid mpUserId);
        /// <summary>
        /// 获取任务推送用户列表
        /// </summary>
        /// <param name="pageIndex">当前页</param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        PagedList<FunongbaoApply> GetForTaskUserList(int pageIndex, int pageSize);
        /// <summary>
        /// 通过funongbaoid获取福农宝最新申请
        /// </summary>
        /// <param name="funongbaoId">福农宝ID</param>
        /// <returns></returns>
        FunongbaoApply GetByFunongbaoId(Guid funongbaoId);

        /// <summary>
        /// 字符串中解析出额度调整方案
        /// </summary>
        /// <param name="limitProgramme">额度调整方案内容</param>
        /// <returns></returns>
        IList<LimitProgrammeDTO> GetLimitProgramme(string limitProgramme);
        /// <summary>
        /// 判断组内是否已经有申请的了
        /// </summary>
        /// <param name="groupNO">组编号</param>
        /// <returns></returns>
        FunongbaoApply ExistGroupApply(string groupNO);

        /// <summary>
        /// 通过家庭组福农宝ID获取当前季度的想应申请记录
        /// </summary>
        /// <param name="funongbaoIds"></param>
        /// <returns></returns>
        IList<FunongbaoApply> GetByFunongbaoIds(Guid[] funongbaoIds);

        /// <summary>
        /// 更新福农宝提交的申请
        /// </summary>
        /// <param name="applys">申请列表</param>
        /// <param name="fnb">受理申请时使用-是否更新福农宝</param>
        /// <returns></returns>
        int UpdateApllys(FunongbaoApply[] applys, bool updateFnb = false);
        /// <summary>
        /// 更新福农宝提交的申请-新
        /// </summary>
        /// <param name="applys">申请列表</param>
        /// <param name="updateApps">同组内的相关更新</param>
        /// <returns></returns>
        int UpdateApllysNew(FunongbaoApply[] applys, IEnumerable<FunongbaoApply> updateApps);

        /// <summary>
        /// 更新福农宝提交的申请
        /// </summary>
        /// <param name="applys">申请列表</param>
        /// <param name="updateApps">满足申请条件后，其他申请列表的更新</param>
        /// <returns></returns>
        int UpdateApllys(FunongbaoApply[] applys, IEnumerable<FunongbaoApply> updateApps);

        /// <summary>
        /// 获取当前日期与导入的日期是否同一季度，保证同一季度只有一条记录
        /// </summary>
        /// <param name="funongbaoId">福农宝ID</param>
        /// <returns></returns>
        FunongbaoApply GetByFunongbaoIdAndDate(Guid funongbaoId);

        #region 测试
        int CancelApply(Guid id);
        #endregion
    }
}
