//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Funongbao.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-05 18:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;
using Ocean.Entity.DTO;


namespace Ocean.Services
{
    public interface IFunongbaoService : IService<Funongbao>
    {
        /// <summary>
        /// 根据搜索条件获取分页数据
        /// </summary>
        PagedList<Funongbao> GetPageList(int pageIndex, int pageSize, Funongbao funongBaoDTO);
        OceanDynamicList<object> GetPageDynamicList(int pageIndex, int pageSize, Funongbao funongBaoDTO, int isAll);
        OceanDynamicList<object> GetPageDynamicList(int pageIndex, int pageSize, Funongbao funongBaoDTO);
        /// <summary>
        /// 通过openid获取福农宝
        /// </summary>
        /// <param name="openid">微信众平台openid</param>
        /// <returns></returns>
        Funongbao GetFunongbaoByOpenid(string openid);

        /// <summary>
        /// 获取组成员-当>1时，则为家庭组
        /// </summary>
        /// <param name="groupNo">组编号</param>
        /// <returns></returns>
        IList<Funongbao> GetGroupByNo(string groupNo);

        /// <summary>
        /// 身份验证-验证成功，同进赋值给Funongbao参数
        /// </summary>
        /// <param name="authItems">验证项</param>
        /// <param name="authFnb">返回通过的福农宝记录</param>
        /// <returns>1-验证通过，2-身份证验证不通过，3-其他项验证不通过,4-都不通过</returns>
        int IdentAuth(Funongbao authItems, out Funongbao authFnb, bool isPassportNO = true);


        /// <summary>
        /// 身份验证-验证成功，同进赋值给Funongbao参数
        /// </summary>
        /// <param name="authItems">验证项</param>
        /// <param name="authFnb">返回通过的福农宝记录</param>
        /// <returns>1-验证通过，2-身份证验证不通过，3-其他项验证不通过,4-都不通过</returns>
        int IdentAuth2(Funongbao authItems, out Funongbao authFnb, bool isPassportNO = true);

        #region 测试
        int CancelIdentAuth(Guid id);
        #endregion
    }
}
