//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpCenter.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-01-28 16:24
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;


namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MpCenterMap : EntityTypeConfiguration<MpCenter>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MpCenter
        /// </summary>
        public MpCenterMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MpCenter");
			//属性
			this.Property(m => m.MpName).HasColumnName("MpName");
			this.Property(m => m.MpHeadImg).HasColumnName("MpHeadImg");
			this.Property(m => m.OriginID).HasColumnName("OriginID");
			this.Property(m => m.AppID).HasColumnName("AppID");
			this.Property(m => m.AppSecret).HasColumnName("AppSecret");
			this.Property(m => m.AccessToken).HasColumnName("AccessToken");
			this.Property(m => m.Token).HasColumnName("Token");
			this.Property(m => m.MpType).HasColumnName("MpType");
			this.Property(m => m.UpdateDate).HasColumnName("UpdateDate");
			this.Property(m => m.GetTokenDate).HasColumnName("GetTokenDate");
			this.Property(m => m.CreateUser).HasColumnName("CreateUser");
			this.Property(m => m.UpdateUser).HasColumnName("UpdateUser");
        }
    }
}
