//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpMaterialItem.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-08 17:25
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MpMaterialItemMap : EntityTypeConfiguration<MpMaterialItem>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MpMaterialItem
        /// </summary>
        public MpMaterialItemMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MpMaterialItem");
			//属性
			this.Property(m => m.MaterialID).HasColumnName("MaterialID");
			this.Property(m => m.ReplyContent).HasColumnName("ReplyContent");
			this.Property(m => m.Title).HasColumnName("Title");
			this.Property(m => m.Description).HasColumnName("Description");
			this.Property(m => m.Summary).HasColumnName("Summary");
			this.Property(m => m.MusicUrl).HasColumnName("MusicUrl");
			this.Property(m => m.HQMusicUrl).HasColumnName("HQMusicUrl");
			this.Property(m => m.PicUrl).HasColumnName("PicUrl");
			this.Property(m => m.Url).HasColumnName("Url");

            //关系
            this.HasRequired(p => p.MpMaterial).WithMany(c => c.MpMaterialItems).HasForeignKey(p => p.MaterialID).WillCascadeOnDelete(false) ;
        }
    }
}
