//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpQrScene.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-03-03 22:19
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MpQrSceneMap : EntityTypeConfiguration<MpQrScene>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MpQrScene
        /// </summary>
        public MpQrSceneMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MpQrScene");
			//属性
			this.Property(m => m.Ticket).HasColumnName("Ticket");
            this.Property(m => m.Title).HasColumnName("Title");
            this.Property(m => m.ActionName).HasColumnName("ActionName");
            this.Property(m => m.TimeoutTicks).HasColumnName("TimeoutTicks");
			this.Property(m => m.Description).HasColumnName("Description");
			this.Property(m => m.SceneId).HasColumnName("SceneId");
			this.Property(m => m.ImgUrl).HasColumnName("ImgUrl");
			this.Property(m => m.UpdateUser).HasColumnName("UpdateUser");
			this.Property(m => m.CreateUser).HasColumnName("CreateUser");
			this.Property(m => m.UpdateDate).HasColumnName("UpdateDate");
        }
    }
}
