//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpRelpyCategory.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-20 09:39
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MpRelpyCategoryMap : EntityTypeConfiguration<MpRelpyCategory>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MpRelpyCategory
        /// </summary>
        public MpRelpyCategoryMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MpRelpyCategory");
			//属性
			this.Property(m => m.Name).HasColumnName("Name");
			this.Property(m => m.Description).HasColumnName("Description");
			this.Property(m => m.Userable).HasColumnName("Userable");
			this.Property(m => m.DesImg).HasColumnName("DesImg");
        }
    }
}
