//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 16:28
// </copyright>
//------------------------------------------------------------------------------

using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class MpUserMap : EntityTypeConfiguration<MpUser>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——MpUser
        /// </summary>
        public MpUserMap()
        {
			// 主键
            this.HasKey(m => m.Id);
			this.Property(m => m.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(m => m.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("MpUser");
			//属性
			this.Property(m => m.OpenID).HasColumnName("OpenID");
			this.Property(m => m.MpID).HasColumnName("MpID");
			this.Property(m => m.MpGroupID).HasColumnName("MpGroupID");
			this.Property(m => m.NickName).HasColumnName("NickName");
            this.Property(m => m.OrginID).HasColumnName("OrginID");
			this.Property(m => m.RemarkName).HasColumnName("RemarkName");
			this.Property(m => m.Sex).HasColumnName("Sex");
			this.Property(m => m.Language).HasColumnName("Language");
			this.Property(m => m.City).HasColumnName("City");
			this.Property(m => m.Province).HasColumnName("Province");
			this.Property(m => m.Country).HasColumnName("Country");
			this.Property(m => m.HeadImgUrl).HasColumnName("HeadImgUrl");
			this.Property(m => m.IsSubscribe).HasColumnName("IsSubscribe");
			this.Property(m => m.UserState).HasColumnName("UserState");
			this.Property(m => m.LocationX).HasColumnName("LocationX");
            this.Property(m => m.LocationY).HasColumnName("LocationY");
			this.Property(m => m.LocationLabel).HasColumnName("LocationLabel");
			this.Property(m => m.SubscribeDate).HasColumnName("SubscribeDate");
			this.Property(m => m.LastVisitDate).HasColumnName("LastVisitDate");
            this.Property(m => m.PasswordKey).HasColumnName("PasswordKey").HasMaxLength(10);
            this.Property(m => m.SessionId).HasColumnName("SessionId").HasMaxLength(50);
            this.Property(f => f.PassportNO).HasColumnName("PassportNO");
            this.Property(f => f.Name).HasColumnName("Name");
            this.Property(f => f.MobilePhone).HasColumnName("MobilePhone");
            this.Property(f => f.IsAuth).HasColumnName("IsAuth");
            this.Property(f => f.SceneId).HasColumnName("SceneId");
            this.Property(f => f.AdminId).HasColumnName("AdminId");
        }
    }
}
