//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Plugin.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginSceneApllyCodeAllower : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginSceneApllyCodeAllower
        /// </summary>
        public PluginSceneApllyCodeAllower()
        {
        }
		
		/// <summary>
		/// 自定义名称
		/// </summary>
        public string GYH { set; get; }

		/// <summary>
		/// 
		/// </summary>
        public string Name { set; get; }


		/// <summary>
		/// 插件类型
		/// </summary>
        public Guid MpUserId { set; get; }

		
    }
}
