//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginAllowUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginAllowUser : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginAllowUser
        /// </summary>
        public PluginAllowUser()
        {
        }

        /// <summary>
        /// 用户真实姓名
        /// </summary>
        public string Name { set; get; }
		/// <summary>
		/// 用户电话号码
		/// </summary>
        public string Phone { set; get; }

		/// <summary>
		/// 证件类型
		/// </summary>
        //public string CertType { set; get; }

        /// <summary>
        /// 证件号码
        /// </summary>
        public string CertNo { set; get; }

        /// <summary>
        /// 证件号码后四位
        /// </summary>
        public string CertNo2 { set; get; }

		/// <summary>
		/// 交易笔数
		/// </summary>
        public int TradeNo { set; get; }

        /// <summary>
        /// 微信号码
        /// </summary>
        public string MPUserID { set; get; }

		
    }
}
