//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBaseStyle.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginBaseStyle : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginBaseStyle
        /// </summary>
        public PluginBaseStyle()
        {
        }
		
		/// <summary>
		/// 插件ID
		/// </summary>
		public Guid PluginBaseId { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string Folder { set; get; }

		/// <summary>
		/// 插件风格代码
		/// </summary>
		public string IdentCode { set; get; }

		/// <summary>
		/// 原始图片地址
		/// </summary>
		public string SourcePic { set; get; }

		/// <summary>
		/// 预览图片地址
		/// </summary>
		public string PreviewPic { set; get; }

		/// <summary>
		/// 工具栏显示的小图片
		/// </summary>
		public string Pic { set; get; }

		/// <summary>
		/// 是否审核通过
		/// </summary>
		public bool IsPass { set; get; }

		/// <summary>
		/// 是否默认
		/// </summary>
		public int IsDefault { set; get; }

		/// <summary>
		/// 是否多项结果
		/// </summary>
		public int IsMulti { set; get; }

    }
}
