//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginUsed.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginUsed : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginUsed
        /// </summary>
        public PluginUsed()
        {
        }
		
		/// <summary>
		/// 用户ID
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 插件ID
		/// </summary>
		public Guid PluginId { set; get; }

		/// <summary>
		/// 可使用数量
		/// </summary>
		public int HasUseCount { set; get; }

		private DateTime usedate;
		/// <summary>
		/// 最近使用日期
		/// </summary>
		public DateTime UseDate
		{
			set { usedate = value; }
			get
			{
				if (usedate < new DateTime(1900, 1, 1))
				{
					usedate = new DateTime(1900, 1, 1);
				}
				return usedate;
			}
		}
    }
}
