//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBase.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginBase : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginBase
        /// </summary>
        public PluginBase()
        {
        }
		
		/// <summary>
		/// 关联插件ID(用户免费与收费只存在一种)
		/// </summary>
        public Guid PluginVersionId { set; get; }

		/// <summary>
		/// 插件类型
		/// </summary>
		public Guid CategoryId { set; get; }

		/// <summary>
		/// 标识码
		/// </summary>
		public string IdentCode { set; get; }

		/// <summary>
		/// 插件名称
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 文件夹名称
		/// </summary>
		public string FolderName { set; get; }

		/// <summary>
		/// 管理地址
		/// </summary>
		public string ManageUrl { set; get; }

		/// <summary>
		/// 原始图片地址
		/// </summary>
		public string SourcePic { set; get; }

		/// <summary>
		/// 预览图片地址
		/// </summary>
		public string PreviewPic { set; get; }

		/// <summary>
		/// 工具栏显示的小图片
		/// </summary>
		public string Pic { set; get; }

		/// <summary>
		/// 是否在页面显示New
		/// </summary>
		public int IsNew { set; get; }

		/// <summary>
		/// 是否必须
		/// </summary>
		public int IsMust { set; get; }

		/// <summary>
		/// 是否可使用多个
		/// </summary>
		public int IsMulti { set; get; }

		/// <summary>
		/// 是否在设计时显示
		/// </summary>
		public int IsEdit { set; get; }

		/// <summary>
		/// 是否审核通过
		/// </summary>
		public int IsPass { set; get; }

		/// <summary>
		/// 是否有收费应用限制
		/// </summary>
		public int IsLimit { set; get; }

		/// <summary>
		/// 控件值(xml存储)
		/// </summary>
		public string Value { set; get; }

		/// <summary>
		/// 关键词
		/// </summary>
		public string KeyWord { set; get; }

		private DateTime startdate;
		/// <summary>
		/// 开始时间
		/// </summary>
		public DateTime StartDate
		{
			set { startdate = value; }
			get
			{
				if (startdate < new DateTime(1900, 1, 1))
				{
					startdate = new DateTime(1900, 1, 1);
				}
				return startdate;
			}
		}

		private DateTime enddate;
		/// <summary>
		/// 结束时间
		/// </summary>
		public DateTime EndDate
		{
			set { enddate = value; }
			get
			{
				if (enddate < new DateTime(1900, 1, 1))
				{
					enddate = new DateTime(1900, 1, 1);
				}
				return enddate;
			}
		}

		/// <summary>
		/// 适用地区
		/// </summary>
		public string AreaId { set; get; }

		/// <summary>
		/// 使用次数-
		/// </summary>
		public int UseCount { set; get; }

		/// <summary>
		/// 描述说明
		/// </summary>
		public string Description { set; get; }

		/// <summary>
		/// 前台地址
		/// </summary>
		public string Url { set; get; }
    }
}
