//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Plugin.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class PluginSceneVerifyCodeDetail : BaseEntity
    {
        /// <summary>
        /// 实体类-PluginSceneVerifyCodeDetail
        /// </summary>
        public PluginSceneVerifyCodeDetail()
        {
        }
		
		/// <summary>
		/// 自定义名称
		/// </summary>
		public string GYH { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string VerifyCode { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public string ClientPhone { set; get; }

		/// <summary>
		/// 插件类型
		/// </summary>
		public Guid ClientMPID { set; get; }

		/// <summary>
		/// 语言版本ID
		/// </summary>
		public int LeaveCount { set; get; }
        
		private DateTime usedate;
		/// <summary>
		/// 
		/// </summary>
		public DateTime UseDate
		{
			set { usedate = value; }
			get
			{
				if (usedate < new DateTime(1900, 1, 1))
				{
					usedate = new DateTime(1900, 1, 1);
				}
				return usedate;
			}
		}

    }
}
