//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginAllowUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
    public partial class VoteItemMap : EntityTypeConfiguration<VoteItem>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——PluginAllowUser
        /// </summary>
        public VoteItemMap()
        {
			// 主键
            this.HasKey(p => p.Id);
            this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("VoteItem");
			//属性
            this.Property(p => p.VoteParentId).HasColumnName("VoteParentId");
            this.Property(p => p.ItemName).HasColumnName("ItemName");
            //this.Property(p => p.CertType).HasColumnName("CertType");
            this.Property(p => p.ItemPic).HasColumnName("ItemPic");
            this.Property(p => p.VoteCount).HasColumnName("VoteCount");
            this.Property(p => p.ItemAuthor).HasColumnName("ItemAuthor");
            this.Property(p => p.ItemSummary).HasColumnName("ItemSummary");
        }
    }
}
