//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginAllowUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
    public partial class VoteBaseMap : EntityTypeConfiguration<VoteBase>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——VoteBase
        /// </summary>
        public VoteBaseMap()
        {
			// 主键
            this.HasKey(p => p.Id);
            this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("VoteBase");
			//属性
            this.Property(p => p.VoteTitle).HasColumnName("VoteTitle");
            this.Property(p => p.VoteCount).HasColumnName("VoteCount");
            //this.Property(p => p.CertType).HasColumnName("CertType");
            this.Property(p => p.VoteStartDate).HasColumnName("VoteStartDate");
            this.Property(p => p.VoteEndDate).HasColumnName("VoteEndDate");
        }
    }
}
