//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginUsed.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;
using Ocean.Core;
using Ocean.Entity.DTO;


namespace Ocean.Services
{
    public class ScoreConsumeInfoService : ServiceBase<ScoreConsumeInfo>, IScoreConsumeInfoService
    {
        public ScoreConsumeInfoService(IRepository<ScoreConsumeInfo> ScoreConsumeInfoRepository, IDbContext context)
            : base(ScoreConsumeInfoRepository, context)
        {
        }
        public PagedList<ScoreConsumeInfo> GetConsumeScoreList(Guid gid, int pageIndex, int pageSize)
        {
            int currentMonth = DateTime.Now.Month;
            int year = DateTime.Now.Year;
            DateRule dateRule = DateRuleList.DateRules.Where(d => d.Months.Where(m => m == currentMonth).Count() > 0).First();
            string sql = "select * from ScoreConsumeInfo where MpUserId = '" + gid + "' order by CreateDate desc ";

            return this.GetPageList<ScoreConsumeInfo>(sql, pageIndex, pageSize);
        }

    }
}
