//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginUsed.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;
using Ocean.Core;
using Ocean.Core.Data.OrderBy;

namespace Ocean.Services
{
    public class ScoreUserService : ServiceBase<ScoreUser>, IScoreUserService
    {
        public ScoreUserService(IRepository<ScoreUser> ScoreUserRepository, IDbContext context)
            : base(ScoreUserRepository, context)
        {
        }

        public PagedList<ScoreUser> GetPageList(int PageIndex, int PageSize, ScoreUser scoreUserDTO)
        {
            IQueryable<ScoreUser> query = base.Table;

            
            if (!string.IsNullOrWhiteSpace(scoreUserDTO.ClientPhone))
            {
                query = query.Where(k => k.ClientPhone == scoreUserDTO.ClientPhone);
            }

            if (!string.IsNullOrWhiteSpace(scoreUserDTO.ClientName))
            {
                query = query.Where(k => k.ClientName == scoreUserDTO.ClientName);
            }

            query = query.OrderByDescending("CreateDate");
            int count = query.Count();

            if (PageIndex == 1)
            {
                query = query.Take<ScoreUser>(PageSize);
            }
            else
            {
                query = query.Skip<ScoreUser>((PageIndex - 1) * PageSize).Take<ScoreUser>(PageSize);
            }

            PagedList<ScoreUser> pageItems = new PagedList<ScoreUser>(query.ToList(), PageIndex, PageSize);
            pageItems.TotalItemCount = count;
            return pageItems;
        }
    }
}
