//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Branch.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 20:02
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;

namespace Ocean.Entity.Mapping
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class BranchMap : EntityTypeConfiguration<Branch>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——Branch
        /// </summary>
        public BranchMap()
        {
			// 主键
            this.HasKey(b => b.Id);
			this.Property(b => b.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(b => b.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("Branch");
			//属性
			this.Property(b => b.Name).HasColumnName("Name");
			this.Property(b => b.Logo).HasColumnName("Logo");
			this.Property(b => b.Address).HasColumnName("Address");
			this.Property(b => b.Phone).HasColumnName("Phone");
			this.Property(b => b.MobilePhone).HasColumnName("MobilePhone");
			this.Property(b => b.ContactName).HasColumnName("ContactName");
			this.Property(b => b.Longitude).HasColumnName("Longitude");
			this.Property(b => b.Latitude).HasColumnName("Latitude");
			this.Property(b => b.Status).HasColumnName("Status");
			this.Property(b => b.Discription).HasColumnName("Discription");
            this.Property(b => b.Type).HasColumnName("Type");
        }
    }
}
