//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Branch.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 20:03
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;
using Ocean.Entity.DTO;

namespace Ocean.Services
{
    public interface IBranchService : IService<Branch>
    {
        /// <summary>
        /// 根据搜索条件获取分页数据
        /// </summary>
        PagedList<Branch> GetPageList(int pageIndex, int pageSize, BranchDTO branchDTO);

        /// <summary>
        /// 冻结周边网点
        /// </summary>
        bool FreezeBranch(Guid id);

        /// <summary>
        /// 解冻周边网点
        /// </summary>
        bool UnFreezeBranch(Guid id);

        IList<BranchDTO> GetBranch(double locationx, double locationy);
    }
}
