//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class PosMap : EntityTypeConfiguration<Pos>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——Pos
        /// </summary>
        public PosMap()
        {
			// 主键
            this.HasKey(p => p.Id);
			this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("Pos");
			//属性
			this.Property(p => p.MpUserId).HasColumnName("MpUserId");
			this.Property(p => p.VendorAddress).HasColumnName("VendorAddress");
			this.Property(p => p.VendorPic).HasColumnName("VendorPic");
			this.Property(p => p.VendorNO).HasColumnName("VendorNO");
			this.Property(p => p.VendorName).HasColumnName("VendorName");
			this.Property(p => p.TerminalNO).HasColumnName("TerminalNO");
			this.Property(p => p.InstallAddress).HasColumnName("InstallAddress");
			this.Property(p => p.DeductRate).HasColumnName("DeductRate");
			this.Property(p => p.MobilePhones).HasColumnName("MobilePhones");
			this.Property(p => p.MpUserIds).HasColumnName("MpUserIds");
        }
    }
}
