//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginAllowUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
    public partial class ScoreStoreItemMap : EntityTypeConfiguration<ScoreStoreItem>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——ScoreStoreItem
        /// </summary>
        public ScoreStoreItemMap()
        {
			// 主键
            this.HasKey(p => p.Id);
            this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("ScoreStoreItem");
            //属性
            this.Property(p => p.BaseId).HasColumnName("BaseId");
            this.Property(p => p.ItemName).HasColumnName("ItemName");
            this.Property(p => p.ItemPic).HasColumnName("ItemPic");
            this.Property(p => p.NeedPoint).HasColumnName("NeedPoint");
            this.Property(p => p.TotalCount).HasColumnName("TotalCount");
            this.Property(p => p.LeftCount).HasColumnName("LeftCount");
            this.Property(p => p.ItemSummary).HasColumnName("ItemSummary");
            this.Property(p => p.PrizePercent).HasColumnName("PrizePercent");
            this.Property(p => p.PrizeAngle).HasColumnName("PrizeAngle");
            this.Property(p => p.PluginName).HasColumnName("PluginName");
            this.Property(p => p.AliasName).HasColumnName("AliasName");
            this.Property(p => p.VirtualGift).HasColumnName("VirtualGift");
        }
    }
}
