//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBase.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;


namespace Ocean.Services
{
    public interface IPluginBaseService : IService<PluginBase>
    {
        /// <summary>
        /// 获取插件［开通或未开通］列表
        /// </summary>
        /// <param name="pageIndex">当前页</param>
        /// <param name="pageSize">每页大小</param>
        /// <param name="cid">类别id</param>
        /// <returns></returns>
        OceanDynamicList<object> GetPluginList(int pageIndex, int pageSize, Guid cid);
    }
}
