//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBaseStyle.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;


namespace Ocean.Services
{
    public interface IPluginBaseStyleService : IService<PluginBaseStyle>
    {
        /// <summary>
        /// 获取风格列表
        /// </summary>
        /// <param name="pluginBaseId">插件ID</param>
        /// <returns></returns>
        IList<PluginBaseStyle> GetStyleList(Guid pluginBaseId);
    }
}
