//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Plugin.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;


namespace Ocean.Services
{
    public interface IPluginService : IService<Plugin>
    {
        /// <summary>
        /// 保存插件
        /// </summary>
        /// <param name="pluginDto">插件数据</param>
        /// <returns></returns>
        Plugin SavePlugin(Plugin pluginDto);

        /// <summary>
        /// 更新插件
        /// </summary>
        /// <param name="pluginDto"></param>
        void UpdatePlugin(Plugin pluginDto, Plugin plugin);

        /// <summary>
        /// 开通插件
        /// </summary>
        /// <param name="pluginBaseId">插件ID</param>
        /// <returns></returns>
        Guid OpenPlugin(Guid pluginBaseId, string isMulti);

        /// <summary>
        /// 删除插件
        /// </summary>
        /// <param name="pluginId">插件ID</param>
        void DelPlugin(Guid pluginId);

        /// <summary>
        /// 重置插件
        /// </summary>
        /// <param name="pluginId"></param>
        void ResetPlugin(Guid pluginId);

        /// <summary>
        /// 插件搜索
        /// </summary>
        /// <param name="name">插件名称</param>
        /// <param name="pageIndex">当前页</param>
        /// <param name="pageSize">每页记录数</param>
        /// <returns></returns>
        PagedList<Plugin> SeachPluginList(string name, int pageIndex, int pageSize);
    }
}
