//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBase.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:37
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;
using Ocean.Core;


namespace Ocean.Services
{
    public class PluginBaseService : ServiceBase<PluginBase>, IPluginBaseService
    {
		public PluginBaseService(IRepository<PluginBase> pluginBaseRepository, IDbContext context)
            : base(pluginBaseRepository, context)
        {
        }
        public OceanDynamicList<object> GetPluginList(int pageIndex, int pageSize, Guid cid)
        {
            string queryString = "select sp.Id, p.Id as PluginId,p.IsMulti,sp.Name, p.Name as PluginName, sp.IsShow,p.IsPass, sp.IsOpen,p.IsEdit,sp.CategoryId, sp.LanguageId, sp.StyleId, sp.StyleFolder, sp.Value,sp.Sort,  p.CreateDate as PluginCreateDate,sp.CreateDate,p.Url, sp.StartDate,p.EndDate from PluginBase p left join Plugin sp on p.Id=sp.PluginBaseId " + (cid !=Guid.Empty ? (" where p.CategoryId='" + cid.ToString() + "'") : "") + " order by p.CreateDate desc";
            return this.GetDynamicList(queryString, pageIndex, pageSize);
        }
    }
}
