//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:58
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;


namespace Ocean.Services
{
    public interface IPosApplyService : IService<PosApply>
    {
        /// <summary>
        /// 获取POS申请记录
        /// </summary>
        /// <param name="PageIndex">当前页</param>
        /// <param name="PageSize">每页记录数</param>
        /// <param name="posApplyDTO">查询条件</param>
        /// <returns></returns>
        OceanDynamicList<object> GetPageList(int PageIndex, int PageSize, PosApply posApplyDTO);
    }
}
