//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:58
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core;


namespace Ocean.Services
{
    public interface IPosService : IService<Pos>
    {
        /// <summary>
        /// POS绑定
        /// </summary>
        /// <param name="pos"></param>
        /// <returns></returns>
        int PosBind(Pos pos);

        /// <summary>
        /// 获取POS存量清单列表
        /// </summary>
        /// <param name="PageIndex">当前页码</param>
        /// <param name="PageSize">每页大小</param>
        /// <param name="posDTO">查询DTO</param>
        /// <returns></returns>
        OceanDynamicList<object> GetPageDynamicList(int PageIndex, int PageSize,Pos posDTO);

        /// <summary>
        /// 查看是否已存在POS
        /// </summary>
        /// <param name="pos">Pos</param>
        /// <param name="oldPos">旧POS</param>
        /// <param name="isVendorNo">是否需要商户号参数</param>
        /// <returns></returns>
        int ExistPos(Pos pos, out Pos oldPos, bool isVendorNo);
    }
}
