//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PosApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:58
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;
using Ocean.Core.Utility;


namespace Ocean.Services
{
    public class PosApplyService : ServiceBase<PosApply>, IPosApplyService
    {
		public PosApplyService(IRepository<PosApply> posApplyRepository, IDbContext context)
            : base(posApplyRepository, context)
        {
        }

        public Core.OceanDynamicList<object> GetPageList(int PageIndex, int PageSize, PosApply posApplyDTO)
        {
            string sql = "select pa.Name,pa.MobilePhone,p.* from PosApply p inner join PosAuth pa on p.MpUserId=pa.MpUserId where 1=1";

            if (posApplyDTO.Status>-1)
            {
                sql += " and Status=" + posApplyDTO.Status.ToString();
            }

            if (posApplyDTO.ProcessStatus>-1)
            {
                if ((int)posApplyDTO.ProcessStatus == 99)
                {
                    sql += " and (ProcessStatus=1 or ProcessStatus=2 or ProcessStatus=3)";
                }
                else
                {
                    sql += " and ProcessStatus=" + posApplyDTO.ProcessStatus.ToString();
                }
            }

            if (posApplyDTO.AssignStatus>-1)
            {
                sql += " and AssignStatus=" + posApplyDTO.AssignStatus.ToString();
            }

            if (posApplyDTO.PastDueId.HasValue)
            {
                DateTime dtPastDue = DateTime.Now.AddMonths(-1);

                if ((int)posApplyDTO.PastDueId == 1)
                {
                    sql += " and p.CreateDate<'" + dtPastDue + "'";
                }

                if ((int)posApplyDTO.PastDueId == 0)
                {
                    sql += " and p.CreateDate>='" + dtPastDue + "'";
                }
            }

            if (posApplyDTO.StartDate.HasValue)
            {
                sql += " and p.CreateDate>='" + posApplyDTO.StartDate.ToString() + "'";
            }

            if (posApplyDTO.EndDate.HasValue)
            {
                DateTime dtEndDate = ((DateTime)posApplyDTO.EndDate).AddDays(1);
                sql += " and p.CreateDate<='" + dtEndDate + "'";
            }

            if (!string.IsNullOrWhiteSpace(posApplyDTO.VendorName))
            {
                sql += " and VendorName like '%" + StringHelper.SqlEscape(posApplyDTO.VendorName) + "%'";
            }

            if (!string.IsNullOrWhiteSpace(posApplyDTO.VendorAddress))
            {
                sql += " and VendorAddress like '%" + StringHelper.SqlEscape(posApplyDTO.VendorAddress) + "%'";
            }
            
            if (!string.IsNullOrWhiteSpace(posApplyDTO.AssignCustomerManager))
            {
                sql += " and AssignCustomerManager like '%" + StringHelper.SqlEscape(posApplyDTO.AssignCustomerManager) + "%'";
            }

            sql += " order by p.CreateDate desc";
            return this.GetDynamicList(sql,PageIndex, PageSize);
        }
    }
}
