//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginBase.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
	public partial class PluginBaseMap : EntityTypeConfiguration<PluginBase>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——PluginBase
        /// </summary>
        public PluginBaseMap()
        {
			// 主键
            this.HasKey(p => p.Id);
			this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
			this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("PluginBase");
			//属性
			this.Property(p => p.PluginVersionId).HasColumnName("PluginVersionId");
			this.Property(p => p.CategoryId).HasColumnName("CategoryId");
			this.Property(p => p.IdentCode).HasColumnName("IdentCode");
			this.Property(p => p.Name).HasColumnName("Name");
			this.Property(p => p.FolderName).HasColumnName("FolderName");
			this.Property(p => p.ManageUrl).HasColumnName("ManageUrl");
			this.Property(p => p.SourcePic).HasColumnName("SourcePic");
			this.Property(p => p.PreviewPic).HasColumnName("PreviewPic");
			this.Property(p => p.Pic).HasColumnName("Pic");
			this.Property(p => p.IsNew).HasColumnName("IsNew");
			this.Property(p => p.IsMust).HasColumnName("IsMust");
			this.Property(p => p.IsMulti).HasColumnName("IsMulti");
			this.Property(p => p.IsEdit).HasColumnName("IsEdit");
			this.Property(p => p.IsPass).HasColumnName("IsPass");
			this.Property(p => p.IsLimit).HasColumnName("IsLimit");
			this.Property(p => p.Value).HasColumnName("Value");
			this.Property(p => p.KeyWord).HasColumnName("KeyWord");
			this.Property(p => p.StartDate).HasColumnName("StartDate");
			this.Property(p => p.EndDate).HasColumnName("EndDate");
			this.Property(p => p.AreaId).HasColumnName("AreaId");
			this.Property(p => p.UseCount).HasColumnName("UseCount");
			this.Property(p => p.Description).HasColumnName("Description");
			this.Property(p => p.Url).HasColumnName("Url");
        }
    }
}
