//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginAllowUser.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Ocean.Entity;
using Ocean.Entity;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类-数据表映射——
    /// </summary>    
    public partial class PluginAllowUserMap : EntityTypeConfiguration<PluginAllowUser>
    {
        /// <summary>
        /// 实体类-数据表映射构造函数——PluginAllowUser
        /// </summary>
        public PluginAllowUserMap()
        {
			// 主键
            this.HasKey(p => p.Id);
            this.Property(p => p.Id).HasColumnName("Id").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(p => p.CreateDate).HasColumnName("CreateDate");
			// 表 & 列映射
            this.ToTable("PluginAllowUser");
			//属性
            this.Property(p => p.Name).HasColumnName("Name");
            this.Property(p => p.Phone).HasColumnName("Phone");
            //this.Property(p => p.CertType).HasColumnName("CertType");
            this.Property(p => p.CertNo).HasColumnName("CertNo");
            this.Property(p => p.CertNo2).HasColumnName("CertNo2");
            this.Property(p => p.TradeNo).HasColumnName("TradeNo");
            this.Property(p => p.MPUserID).HasColumnName("MPUserID");
        }
    }
}
