//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpUserGroup.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 13:45
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;


namespace Ocean.Services
{
    public interface IMpUserGroupService : IService<MpUserGroup>
    {
        /// <summary>
        /// 获取系统默认分组黑名单实体
        /// </summary>
        /// <param name="gName"></param>
        /// <returns></returns>
        MpUserGroup GetSystemGroup(string gName);
    }
}
