//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpCenter.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-01-28 16:48
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;

namespace Ocean.Services
{
    public class MpCenterService : ServiceBase<MpCenter>, IMpCenterService
    {
        private readonly ILoanService _loanService;
        public MpCenterService(IRepository<MpCenter> mpCenterRepository, IDbContext context, ILoanService loanService)
            : base(mpCenterRepository, context)
        {
            this._loanService = loanService;
        }
        public string GetByLoan()
        {
            var mp = _loanService.GetById(new Guid("1A443BED-E8C1-471F-97A7-10DD6A6ACFB2"));
            return "";
        }
    }
}
