//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpQrScene.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-03-03 22:25
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;


namespace Ocean.Services
{
    public class MpQrSceneService : ServiceBase<MpQrScene>, IMpQrSceneService
    {
		public MpQrSceneService(IRepository<MpQrScene> mpQrSceneRepository, IDbContext context)
            : base(mpQrSceneRepository, context)
        {
        }
        public int GetMaxSceneId(int actionname)
        {
            MpQrScene mp= this.GetALL().Where(x=>x.ActionName==actionname).OrderByDescending(x => x.SceneId).FirstOrDefault();
            if (mp==null)
            {
                return actionname == 0 ? 200000 : 1;
            }
            else
            {
                return mp.SceneId;
            }
        }
    }
}
