//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpReply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-20 09:40
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;
using Newtonsoft.Json;


namespace Ocean.Services
{
    public class MpReplyService : ServiceBase<MpReply>, IMpReplyService
    {
        private readonly IMpMaterialService MpMaterialService;
        private readonly IMpMaterialItemService MpMaterialItemService;
        public MpReplyService(IRepository<MpReply> mpReplyRepository, IDbContext context, IMpMaterialService MpMaterialService,IMpMaterialItemService MpMaterialItemService)
            : base(mpReplyRepository, context)
        {
            this.MpMaterialService = MpMaterialService;
            this.MpMaterialItemService = MpMaterialItemService;
        }

        public MpReply GetByAction(string action)
        {
            return this.GetALL(m => m.Action == action).FirstOrDefault();
        }

        public bool SaveMpRepy(string data)
        {
            try
            {
                this.BeginTransaction();
                MpReply reply = JsonConvert.DeserializeObject<MpReply>(data);
                if (reply.Id == Guid.Empty)
                {
                    if (reply.MpMaterial.Id == Guid.Empty && reply.MpMaterial.TypeName == "text")
                    {
                        reply.MpMaterial = MpMaterialService.SaveByText(reply.MpMaterial, reply.MpMaterial.MpMaterialItems.FirstOrDefault().ReplyContent);
                    }
                    reply.MaterialID = reply.MpMaterial.Id;
                    reply.MpMaterial = null;
                    this.Insert(reply);
                }
                else
                {
                    MpReply oldreply = this.GetALL(m => m.Id == reply.Id).FirstOrDefault();
                    
                    if (reply.MpMaterial.Id == Guid.Empty && reply.MpMaterial.TypeName == "text")
                    {
                        reply.MpMaterial = MpMaterialService.SaveByText(reply.MpMaterial, reply.MpMaterial.MpMaterialItems.FirstOrDefault().ReplyContent);
                    }
                    else if(oldreply.MpMaterial.TypeName=="text")
                    {
                        if (reply.MpMaterial.TypeName=="text")
                        {
                            MpMaterialItemService.Update(reply.MpMaterial.MpMaterialItems.FirstOrDefault());
                            MpMaterialService.Update(reply.MpMaterial);                            
                        }
                        else
                        {                            
                            MpMaterialItemService.Delete(oldreply.MpMaterial.MpMaterialItems.FirstOrDefault());
                            MpMaterialService.Delete(oldreply.MpMaterial);
                        }                       
                    }
                    reply.MaterialID = reply.MpMaterial.Id;
                    reply.MpMaterial = null;
                    this.Update(reply);
                }

                this.Commit();
                return true;

            }
            catch (Exception e)
            {
                this.Rollback();
                return false;
            }
        }
    }
}
