//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="MpUserGroup.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 13:45
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;


namespace Ocean.Services
{
    public class MpUserGroupService : ServiceBase<MpUserGroup>, IMpUserGroupService
    {
        public MpUserGroupService(IRepository<MpUserGroup> mpUserGroupRepository, IDbContext context)
            : base(mpUserGroupRepository, context)
        {

        }
        public MpUserGroup GetSystemGroup(string gName)
        {
            string sql = "select * from MpUserGroup where IsSystem=1 and Name =@name";
            Dictionary<string, object> parms = new Dictionary<string, object>();
            parms.Add("name", gName);
            return this.GetUnique(sql, parms);
        }


    }
}
