//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class BaoXian : BaseEntity
    {
        /// <summary>
        /// 实体类-保险单
        /// </summary>
        public BaoXian()
        {
        }

        public Guid MpUserId { set; get; }
		/// <summary>
		/// 投保公司
		/// </summary>
        public string TouBaoGongSi { set; get; }

        /// <summary>
        /// 投保人
        /// </summary>
        public string TouBaoRen { set; get; }

        /// <summary>
        /// 车牌号码
        /// </summary>
        public string ChePai { set; get; }

        private DateTime qiBaoDate;
        /// <summary>
        /// 起保日期
        /// </summary>
        public DateTime QiBaoDate
        {
            set { qiBaoDate = value; }
            get
            {
                if (qiBaoDate < new DateTime(1900, 1, 1))
                {
                    qiBaoDate = new DateTime(1900, 1, 1);
                }
                return qiBaoDate;
            }
        }


        /// <summary>
        /// 保险期限
        /// </summary>
        public int BaoXianQiXian { set; get; }

        /// <summary>
        /// 后四位
        /// </summary>
        public string HouSiWei { set; get; }

        private DateTime dengJiDate;
        /// <summary>
        /// 登记时间
        /// </summary>
        public DateTime DengJiDate
        {
            set { dengJiDate = value; }
            get
            {
                if (dengJiDate < new DateTime(1900, 1, 1))
                {
                    dengJiDate = new DateTime(1900, 1, 1);
                }
                return dengJiDate;
            }
        }

        /// <summary>
        /// 保险费
        /// </summary>
        public decimal BaoXianFei { set; get; }
        /// <summary>
        /// 车船税
        /// </summary>
        public decimal CheChuanSui { set; get; }
        /// <summary>
        /// 来源
        /// </summary>
        public string LaiYuan { set; get; }

        /// <summary>
        /// 险种
        /// </summary>
        public int XianZhong { set; get; }

        /// <summary>
        /// 正本照片
        /// </summary>
        public string VendorPic1 { set; get; }
        /// <summary>
        /// 副本照片
        /// </summary>
        public string VendorPic2 { set; get; }
    }
}
