//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class Complain : BaseEntity
    {
        /// <summary>
        /// 实体类-投诉
        /// </summary>
        public Complain()
        {
        }

		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 被投诉姓名
		/// </summary>
        public string Name { set; get; }

        /// <summary>
        /// 被投诉Phone
        /// </summary>
        public string Phone { set; get; }

        /// <summary>
        /// 联系姓名
        /// </summary>
        public string ContactName { set; get; }

		/// <summary>
        /// 联系电话
		/// </summary>
        public string ContactPhone { set; get; }

		/// <summary>
		/// 投诉内容
		/// </summary>
        public string ComplainContent { set; get; }

        /// <summary>
        /// 处理结果[1满意 2不满意 3未处理]
        /// </summary>
        public int ProcessStatus { set; get; }

        /// <summary>
        /// 处理备注
        /// </summary>
        public string ProcessResult { set; get; }

        /// <summary>
        /// 处理时间
        /// </summary>
        public DateTime? ProcessDate
        {
            set;
            get;
        }
        
    }
}
