//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class DrivingLicense : BaseEntity
    {
        /// <summary>
        /// 实体类-驾驶证
        /// </summary>
        public DrivingLicense()
        {
        }

		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 证件号码
		/// </summary>
        public string CertNo { set; get; }

        /// <summary>
        /// 姓名
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// 性别
        /// </summary>
        public int Sex { set; get; }

		/// <summary>
        /// 国籍
		/// </summary>
        public string Nationality { set; get; }

		/// <summary>
		/// 地址
		/// </summary>
        public string Address { set; get; }


        private DateTime birthday;
        public DateTime Birthday
        {
            set { birthday = value; }
            get
            {
                if (birthday < new DateTime(1900, 1, 1))
                {
                    birthday = new DateTime(1900, 1, 1);
                }
                return birthday;
            }
        }
        private DateTime issueDate;
        /// <summary>
        /// 发证时间
        /// </summary>
        public DateTime IssueDate
        {
            set { issueDate = value; }
            get
            {
                if (issueDate < new DateTime(1900, 1, 1))
                {
                    issueDate = new DateTime(1900, 1, 1);
                }
                return issueDate;
            }
        }

        /// <summary>
        /// 准驾类型 B2,C1之类
        /// </summary>
        public int Class { set; get; }

        private DateTime validFrom;
        /// <summary>
        /// 发证时间
        /// </summary>
        public DateTime ValidFrom
        {
            set { validFrom = value; }
            get
            {
                if (validFrom < new DateTime(1900, 1, 1))
                {
                    validFrom = new DateTime(1900, 1, 1);
                }
                return validFrom;
            }
        }
		/// <summary>
		/// 有效期限
		/// </summary>
        public int ValidFor { set; get; }


        /// <summary>
        /// 照片
        /// </summary>
        public string VendorPic { set; get; }
    }
}
