//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Pos.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-05-10 17:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class VehicleLicense : BaseEntity
    {
        /// <summary>
        /// 实体类-行驶证
        /// </summary>
        public VehicleLicense()
        {
        }

		/// <summary>
		/// 微信用户Id
		/// </summary>
		public Guid MpUserId { set; get; }

		/// <summary>
		/// 车牌号码
		/// </summary>
        public string PlateNo { set; get; }

        /// <summary>
        /// 车辆类型
        /// </summary>
        public int VehicleType { set; get; }

		/// <summary>
        /// 所有者
		/// </summary>
        public string Owner { set; get; }

		/// <summary>
		/// 地址
		/// </summary>
        public string Address { set; get; }

		/// <summary>
		/// 车辆性质
		/// </summary>
        public int UseCharacter { set; get; }


        /// <summary>
        /// 品牌型号
        /// </summary>
        public string CarModel { set; get; }

		/// <summary>
		/// 车辆识别代码
		/// </summary>
        public string VIN { set; get; }

		/// <summary>
		/// 发动机号码
		/// </summary>
        public string EngineNo { set; get; }

        private DateTime registerDate;
        /// <summary>
        /// 注册时间
        /// </summary>
        public DateTime RegisterDate
        {
            set { registerDate = value; }
            get
            {
                if (registerDate < new DateTime(1900, 1, 1))
                {
                    registerDate = new DateTime(1900, 1, 1);
                }
                return registerDate;
            }
        }
        private DateTime issueDate;
        /// <summary>
        /// 发证时间
        /// </summary>
        public DateTime IssueDate
        {
            set { issueDate = value; }
            get
            {
                if (issueDate < new DateTime(1900, 1, 1))
                {
                    issueDate = new DateTime(1900, 1, 1);
                }
                return issueDate;
            }
        }


        /// <summary>
        /// 照片
        /// </summary>
        public string VendorPic { set; get; }
    }
}
