//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Funongbao.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 14:21
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class Funongbao : BaseEntity
    {
        /// <summary>
        /// 实体类-Funongbao
        /// </summary>
        public Funongbao()
        {
        }
		
		/// <summary>
		/// 用户ID
		/// </summary>
		public Guid? MpUserId { set; get; }

		/// <summary>
		/// 公众账号openid
		/// </summary>
		public string OpenId { set; get; }

        /// <summary>
        /// 证件类型:1-身份证
        /// </summary>
        public int PassportType { get; set; }
		/// <summary>
		/// 证件号码
		/// </summary>
		public string PassportNO { set; get; }

		/// <summary>
		/// 姓名
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// 手机号码
		/// </summary>
		public string MobilePhone { set; get; }

		/// <summary>
		/// 福农宝号
		/// </summary>
		public string FunongbaoNO { set; get; }

		/// <summary>
		/// 绑定的银行卡号
		/// </summary>
		public string BankNO { set; get; }

        /// <summary>
		/// 总额度
		/// </summary>
        public decimal GroupLimit { set; get; }

		/// <summary>
		/// 当前额度
		/// </summary>
		public decimal CurrentLimit { set; get; }

		/// <summary>
		/// 
		/// </summary>
		public decimal CurrentRates { set; get; }

		/// <summary>
		/// 组编号
		/// </summary>
		public string GroupNO { set; get; }

		/// <summary>
		/// 是否身份认证
		/// </summary>
		public int IsAuth { set; get; }

		/// <summary>
		/// 是否签定协议
		/// </summary>
		public int IsSignAgreement { set; get; }

		/// <summary>
		/// 受理状态
		/// </summary>
		public int ProcessStatus { set; get; }

		/// <summary>
		/// 受理结果
		/// </summary>
		public string ProcessResult { set; get; }

		private DateTime finishdate;
		/// <summary>
		/// 完成更新日期
		/// </summary>
		public DateTime FinishDate
		{
			set { finishdate = value; }
			get
			{
				if (finishdate < new DateTime(1900, 1, 1))
				{
					finishdate = new DateTime(1900, 1, 1);
				}
				return finishdate;
			}
		}
        private DateTime preFinishdate;
        /// <summary>
        /// 完成更新日期
        /// </summary>
        public DateTime PreFinishDate
        {
            set { preFinishdate = value; }
            get
            {
                if (preFinishdate < new DateTime(1900, 1, 1))
                {
                    preFinishdate = new DateTime(1900, 1, 1);
                }
                return preFinishdate;
            }
        }
		/// <summary>
		/// 支行
		/// </summary>
		public string Subbranch { set; get; }

		/// <summary>
		/// 营销人
		/// </summary>
		public string Marketer { set; get; }

        /// <summary>
        /// 福农宝申请详细列表
        /// </summary>
        [JsonIgnore]
        public virtual ICollection<FunongbaoApply> FunongbaoApplies { get; set; }


        /// <summary>
        /// 最近一次方案
        /// </summary>
        [NotMapped]
        public string LimitProgramme
        {
            get;
            set;
        }
        [NotMapped]
        public string ImportQuarter
        { get; set; }
    }
}
