//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="FunongbaoApply.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-07 14:21
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class FunongbaoApply : BaseEntity
    {
        /// <summary>
        /// 实体类-FunongbaoApply
        /// </summary>
        public FunongbaoApply()
        {
        }
		
		/// <summary>
		/// 福农宝ID
		/// </summary>
		public Guid FunongbaoId { set; get; }

        /// <summary>
        /// 福农宝
        /// </summary>
        public virtual Funongbao RFunongbao { get; set; }

        /// <summary>
        /// 原组额度
        /// </summary>
        public decimal PreGroupLimit { set; get; }

        /// <summary>
        /// 原卡额度
        /// </summary>
        public decimal PreLimit { set; get; }

        /// <summary>
        /// 原费率
        /// </summary>
        public decimal PreRates { set; get; }

		/// <summary>
		/// 申请额度
		/// </summary>
		public decimal ApplyLimit { set; get; }

		/// <summary>
		/// 申请费率
		/// </summary>
		public decimal ApplyRates { set; get; }

		/// <summary>
		/// 调整后的限额
		/// </summary>
		public decimal ChangedLimit { set; get; }

		/// <summary>
        /// 调整后的费率
		/// </summary>
		public decimal ChangedRates { set; get; }

		/// <summary>
		/// 受理状态
		/// </summary>
		public int ProcessStatus { set; get; }

		/// <summary>
		/// 受理结果
		/// </summary>
		public string ProcessResult { set; get; }

		/// <summary>
		/// 申请状态-是否可以审批［1-是］
		/// </summary>
        public int ApplyStatus { set; get; }
        /// <summary>
        /// 组成员申请处理状态
        /// </summary>
        public int GroupApplyStatus { set; get; }

        private DateTime applydate;
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime ApplyDate
        {
            set { applydate = value; }
            get
            {
                if (applydate < new DateTime(1900, 1, 1))
                {
                    applydate = new DateTime(1900, 1, 1);
                }
                return applydate;
            }
        }

		private DateTime finishdate;
		/// <summary>
		/// 完成日期
		/// </summary>
		public DateTime FinishDate
		{
			set { finishdate = value; }
			get
			{
				if (finishdate < new DateTime(1900, 1, 1))
				{
					finishdate = new DateTime(1900, 1, 1);
				}
				return finishdate;
			}
		}

		/// <summary>
		/// 支行
		/// </summary>
		public string Subbranch { set; get; }

		/// <summary>
		/// 营销人
		/// </summary>
		public string Marketer { set; get; }

		/// <summary>
		/// 调整方案
		/// </summary>
        public string LimitProgramme { set; get; }

		/// <summary>
		/// 建议额度
		/// </summary>
        public string SuggestionLimit { set; get; }
        /// <summary>
        /// 通知状态
        /// </summary>
        public int NoticeStatus { set; get; }

        /// <summary>
        /// 申请类型［升额还是降额］
        /// </summary>
        public int ApplyType { get; set; }


        /// <summary>
        /// 申请类型临时状态
        /// </summary>
        public int ApplyTypeStatus { get; set; }

        #region search
        /// <summary>
        /// 搜索完成时间
        /// </summary>
        [NotMapped]
        public DateTime FinishEndDate { get; set; }

        [NotMapped]
        public decimal ApplyTempLimit { set; get; }
        [NotMapped]
        public decimal ApplyTempRates { set; get; }
        #endregion
    }
}
