//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Configuration.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-19 09:58
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Entity;
using Ocean.Core.Data;
using Ocean.Data;


namespace Ocean.Services
{
    public class ConfigurationService : ServiceBase<Configuration>, IConfigurationService
    {
		public ConfigurationService(IRepository<Configuration> configurationRepository, IDbContext context)
            : base(configurationRepository, context)
        {
        }

        /// <summary>
        /// 更新指定字段
        /// </summary>
        public void UpdateConfiguration(string Key, string Value)
        {
            Configuration configuration = base.GetUnique(c => c.Key == Key);

            if (configuration != null)
            {
                configuration.Value = Value;
                base.Update(configuration);
            }
            else
            {
                configuration = new Configuration();
                configuration.Key = Key;
                configuration.Value = Value;
                base.Insert(configuration);
            }
        }
    }
}
