//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Branch.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-10 20:02
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class Branch : BaseEntity
    {
        /// <summary>
        /// 实体类-Branch
        /// </summary>
        public Branch()
        {
        }
		
		/// <summary>
		/// 网点名称
		/// </summary>
		public string Name { set; get; }

		/// <summary>
		/// LOGO
		/// </summary>
		public string Logo { set; get; }

		/// <summary>
		/// 地址
		/// </summary>
		public string Address { set; get; }

		/// <summary>
		/// 联系电话
		/// </summary>
		public string Phone { set; get; }

		/// <summary>
		/// 手机号码
		/// </summary>
		public string MobilePhone { set; get; }

		/// <summary>
		/// 联系人
		/// </summary>
		public string ContactName { set; get; }

		/// <summary>
		/// 经度
		/// </summary>
		public string Longitude { set; get; }

		/// <summary>
		/// 纬度
		/// </summary>
		public string Latitude { set; get; }

		/// <summary>
		/// 状态[0:未审核,1:已审核,2:被冻结]
		/// </summary>
		public int Status { set; get; }

		/// <summary>
		/// 描术-预留
		/// </summary>
		public string Discription { set; get; }

        /// <summary>
        /// 网点类型[0:营业网点,1:自助银行,2:ATM]
        /// </summary>
        public int Type { set; get; }
    }
}
