//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="PluginResult.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-22 14:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
    public class XYPluginUser : BaseEntity
    {
        /// <summary>
        /// 实体类-XYPluginUser
        /// </summary>
        public XYPluginUser()
        {
        }

        /// <summary>
        /// 用户ID
        /// </summary>
        public string OpenId { set; get; }

        /// <summary>
        /// 卡号
        /// </summary>
        public string CardNo { set; get; }

        /// <summary>
        /// 交易流水号
        /// </summary>
        public string TradeSeqNo { set; get; }

        /// <summary>
        /// 刮刮卡次数
        /// </summary>
        public int GuaGuaKa { set; get; }

        /// <summary>
        /// 大转盘次数
        /// </summary>
        public int LeftCount { set; get; }

        
    }
}
