//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//
// <copyright file="Configuration.cs">
//		Copyright(c)2014 Ocean.All rights reserved.
//		CLR版本：4.0.30319.239
//		生成时间：2014-02-19 09:57
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ocean.Core;

namespace Ocean.Entity
{
    /// <summary>
    /// 实体类—
    /// </summary>    
	public class Configuration : BaseEntity
    {
        /// <summary>
        /// 实体类-Configuration
        /// </summary>
        public Configuration()
        {
        }
		
		/// <summary>
		/// Key
		/// </summary>
		public string Key { set; get; }

		/// <summary>
		/// Value
		/// </summary>
		public string Value { set; get; }
    }
}
